safe:        false
auto:        false
server:      true
server_port: 4000
name:        lae
title:       milk tea fuzz
baseurl:     /
url:         http://milkteafuzz.com

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    redcarpet
permalink:   /j/:year/:month/:day/:title/
paginate:    4
paginate_path:  j/p/:num
category_dir: /j/
category_title_prefix: ''

rdiscount:
  extensions: []

homelinks:
    - title: resume
      uri: resume
    - title: journal
      uri: j
    - title: git
      uri: http://github.com/liliff
    - title: contact
      uri: contact
