safe:        false
auto:        false
server:      true
server_port: 4000
name:        lae
title:       milk tea fuzz
baseurl:     /
url:         http://milkteafuzz.com

source:      .
destination: ./_site
plugins:     ./_plugins

future:      true
lsi:         false
pygments:    false
markdown:    rdiscount
permalink:   /j/:year/:month/:day/:title/
paginate:    4
paginate_path:  j/p/:num

rdiscount:
  extensions: []

homelinks:
    - title: resume
      uri: resume
    - title: journal
      uri: j
    - title: snippets
      uri: s
    - title: git
      uri: http://github.com/liliff
