base_url = "https://lae.is"
title = "milk tea fuzz"
description = "lae's journal"
default_language = "en"
languages = [
    {code = "ja", search = true }
]
taxonomies = [
    {name = "categories", paginate_by = 5, feed = true},
    {name = "categories", paginate_by = 5, feed = true, lang = "ja"},
    {name = "tags", paginate_by = 5}
]

compile_sass = true
minify_html = true

[markdown]
highlight_code = true
highlight_theme = "charcoal"

[translations]
[translations.en]
logs = "Logs"
about = "Contact"
resume = "Resume"
tags = "Tags"

[translations.ja]
logs = "チラシ"
about = "連絡先"
resume = "履歴書"
tags = "タグ"

[extra]
author = "Musee Ullah"
homelinks = [
    {title = "resume", uri = "resume" },
    {title = "journal", uri = "logs" },
    {title = "git", uri = "https://github.com/lae"},
    {title = "contact", uri = "contact" }
]

[extra.opengraph]
image = "https://i.imgur.com/UXrHtVR.jpg"

[extra.twitter]
creator = "@sleepingkyoto"
